package com.sharry.srouter.plugin.util

import java.util.*

/**
 * register setting
 *
 * @author Sharry [Contact me.](sharrychoochn@gmail.com)
 * @version 1.0
 * @since 4/14/21
 */
class ScanSetting(interfaceName: String) {

    /**
     * scan for classes which implements this interface
     */
    val interfaceName: String

    /**
     * scan result for [.interfaceName]
     * class names in this list
     */
    val classList = ArrayList<String>()

    /**
     * constructor for arouter-auto-register settings
     * @param interfaceName interface to scan
     */
    init {
        this.interfaceName = INTERFACE_PACKAGE_NAME + interfaceName
    }

    companion object {
        const val PLUGIN_NAME = "com.sharry.srouter"

        /**
         * The register code is generated into this class
         */
        const val GENERATE_TO_CLASS_NAME = "com/sharry/srouter/support/SRouterImpl"

        /**
         * you know. this is the class file(or entry in jar file) name
         */
        const val GENERATE_TO_CLASS_FILE_NAME = "$GENERATE_TO_CLASS_NAME.class"

        /**
         * The package name of the interfaces
         */
        const val INTERFACE_PACKAGE_NAME = "com/sharry/srouter/support/"

        /**
         * The register code is generated into this method
         */
        const val GENERATE_TO_METHOD_NAME = "loadRouterMap"

        /**
         * The package name of the class generated by the annotationProcessor
         */
        const val ROUTER_CLASS_PACKAGE_NAME = "com/sharry/srouter/generate"

        /**
         * register method name in class: [.GENERATE_TO_CLASS_NAME]
         */
        const val REGISTER_METHOD_NAME = "register"
    }


}